// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.17.3
// source: pb/svc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSvcRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateSvcRequest) Reset() {
	*x = CreateSvcRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSvcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSvcRequest) ProtoMessage() {}

func (x *CreateSvcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSvcRequest.ProtoReflect.Descriptor instead.
func (*CreateSvcRequest) Descriptor() ([]byte, []int) {
	return file_pb_svc_proto_rawDescGZIP(), []int{0}
}

type CreateSvcReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateSvcReply) Reset() {
	*x = CreateSvcReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSvcReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSvcReply) ProtoMessage() {}

func (x *CreateSvcReply) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSvcReply.ProtoReflect.Descriptor instead.
func (*CreateSvcReply) Descriptor() ([]byte, []int) {
	return file_pb_svc_proto_rawDescGZIP(), []int{1}
}

type UpdateSvcRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateSvcRequest) Reset() {
	*x = UpdateSvcRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSvcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSvcRequest) ProtoMessage() {}

func (x *UpdateSvcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSvcRequest.ProtoReflect.Descriptor instead.
func (*UpdateSvcRequest) Descriptor() ([]byte, []int) {
	return file_pb_svc_proto_rawDescGZIP(), []int{2}
}

type UpdateSvcReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateSvcReply) Reset() {
	*x = UpdateSvcReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSvcReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSvcReply) ProtoMessage() {}

func (x *UpdateSvcReply) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSvcReply.ProtoReflect.Descriptor instead.
func (*UpdateSvcReply) Descriptor() ([]byte, []int) {
	return file_pb_svc_proto_rawDescGZIP(), []int{3}
}

type DeleteSvcRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteSvcRequest) Reset() {
	*x = DeleteSvcRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSvcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSvcRequest) ProtoMessage() {}

func (x *DeleteSvcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSvcRequest.ProtoReflect.Descriptor instead.
func (*DeleteSvcRequest) Descriptor() ([]byte, []int) {
	return file_pb_svc_proto_rawDescGZIP(), []int{4}
}

type DeleteSvcReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteSvcReply) Reset() {
	*x = DeleteSvcReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSvcReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSvcReply) ProtoMessage() {}

func (x *DeleteSvcReply) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSvcReply.ProtoReflect.Descriptor instead.
func (*DeleteSvcReply) Descriptor() ([]byte, []int) {
	return file_pb_svc_proto_rawDescGZIP(), []int{5}
}

type GetSvcRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetSvcRequest) Reset() {
	*x = GetSvcRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSvcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSvcRequest) ProtoMessage() {}

func (x *GetSvcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSvcRequest.ProtoReflect.Descriptor instead.
func (*GetSvcRequest) Descriptor() ([]byte, []int) {
	return file_pb_svc_proto_rawDescGZIP(), []int{6}
}

type GetSvcReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *GetSvcReply) Reset() {
	*x = GetSvcReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSvcReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSvcReply) ProtoMessage() {}

func (x *GetSvcReply) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSvcReply.ProtoReflect.Descriptor instead.
func (*GetSvcReply) Descriptor() ([]byte, []int) {
	return file_pb_svc_proto_rawDescGZIP(), []int{7}
}

func (x *GetSvcReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type ListSvcRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListSvcRequest) Reset() {
	*x = ListSvcRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSvcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSvcRequest) ProtoMessage() {}

func (x *ListSvcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSvcRequest.ProtoReflect.Descriptor instead.
func (*ListSvcRequest) Descriptor() ([]byte, []int) {
	return file_pb_svc_proto_rawDescGZIP(), []int{8}
}

type ListSvcReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListSvcReply) Reset() {
	*x = ListSvcReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSvcReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSvcReply) ProtoMessage() {}

func (x *ListSvcReply) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSvcReply.ProtoReflect.Descriptor instead.
func (*ListSvcReply) Descriptor() ([]byte, []int) {
	return file_pb_svc_proto_rawDescGZIP(), []int{9}
}

var File_pb_svc_proto protoreflect.FileDescriptor

var file_pb_svc_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x62, 0x2f, 0x73, 0x76, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x22, 0x12, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x76, 0x63, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x76, 0x63, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x12, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x53, 0x76, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x10, 0x0a, 0x0e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x76, 0x63, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x12,
	0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x76, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x76, 0x63, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x0f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x76, 0x63, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x25, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x53, 0x76, 0x63, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x10, 0x0a, 0x0e,
	0x4c, 0x69, 0x73, 0x74, 0x53, 0x76, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0e,
	0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x76, 0x63, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x89,
	0x02, 0x0a, 0x03, 0x53, 0x76, 0x63, 0x12, 0x35, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x76, 0x63, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53,
	0x76, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x76, 0x63, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x35, 0x0a,
	0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x76, 0x63, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x76, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x76, 0x63, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x35, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x76,
	0x63, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x76, 0x63,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x53, 0x76, 0x63, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2c, 0x0a, 0x06, 0x47,
	0x65, 0x74, 0x53, 0x76, 0x63, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x76,
	0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65,
	0x74, 0x53, 0x76, 0x63, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2f, 0x0a, 0x07, 0x4c, 0x69, 0x73,
	0x74, 0x53, 0x76, 0x63, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x76,
	0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x53, 0x76, 0x63, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x15, 0x5a, 0x13, 0x67, 0x72,
	0x70, 0x63, 0x2d, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x3b, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_svc_proto_rawDescOnce sync.Once
	file_pb_svc_proto_rawDescData = file_pb_svc_proto_rawDesc
)

func file_pb_svc_proto_rawDescGZIP() []byte {
	file_pb_svc_proto_rawDescOnce.Do(func() {
		file_pb_svc_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_svc_proto_rawDescData)
	})
	return file_pb_svc_proto_rawDescData
}

var file_pb_svc_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pb_svc_proto_goTypes = []interface{}{
	(*CreateSvcRequest)(nil), // 0: pb.CreateSvcRequest
	(*CreateSvcReply)(nil),   // 1: pb.CreateSvcReply
	(*UpdateSvcRequest)(nil), // 2: pb.UpdateSvcRequest
	(*UpdateSvcReply)(nil),   // 3: pb.UpdateSvcReply
	(*DeleteSvcRequest)(nil), // 4: pb.DeleteSvcRequest
	(*DeleteSvcReply)(nil),   // 5: pb.DeleteSvcReply
	(*GetSvcRequest)(nil),    // 6: pb.GetSvcRequest
	(*GetSvcReply)(nil),      // 7: pb.GetSvcReply
	(*ListSvcRequest)(nil),   // 8: pb.ListSvcRequest
	(*ListSvcReply)(nil),     // 9: pb.ListSvcReply
}
var file_pb_svc_proto_depIdxs = []int32{
	0, // 0: pb.Svc.CreateSvc:input_type -> pb.CreateSvcRequest
	2, // 1: pb.Svc.UpdateSvc:input_type -> pb.UpdateSvcRequest
	4, // 2: pb.Svc.DeleteSvc:input_type -> pb.DeleteSvcRequest
	6, // 3: pb.Svc.GetSvc:input_type -> pb.GetSvcRequest
	8, // 4: pb.Svc.ListSvc:input_type -> pb.ListSvcRequest
	1, // 5: pb.Svc.CreateSvc:output_type -> pb.CreateSvcReply
	3, // 6: pb.Svc.UpdateSvc:output_type -> pb.UpdateSvcReply
	5, // 7: pb.Svc.DeleteSvc:output_type -> pb.DeleteSvcReply
	7, // 8: pb.Svc.GetSvc:output_type -> pb.GetSvcReply
	9, // 9: pb.Svc.ListSvc:output_type -> pb.ListSvcReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_svc_proto_init() }
func file_pb_svc_proto_init() {
	if File_pb_svc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_svc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSvcRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSvcReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSvcRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSvcReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSvcRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSvcReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSvcRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSvcReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSvcRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSvcReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_svc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_svc_proto_goTypes,
		DependencyIndexes: file_pb_svc_proto_depIdxs,
		MessageInfos:      file_pb_svc_proto_msgTypes,
	}.Build()
	File_pb_svc_proto = out.File
	file_pb_svc_proto_rawDesc = nil
	file_pb_svc_proto_goTypes = nil
	file_pb_svc_proto_depIdxs = nil
}
